Update Documentation (concept and input_output)
VIB-PSB/ksrates pull request #2
Opened 2021-03-09 13:46 UTC by Cecilia-Sensalari

- concept.rst: shortened first section and restructured "explained example"
- input_output.rst: completed file lists and descriptions
- usage.rst: added path to output filenames to tell where they are generated, peak database description, --n-threads suggestion, description of the multi-page PDF of ortholog Ks distributions

2021-03-15 15:24 UTC, lohausr requested changes
See my edits and comments.

2021-03-15 15:24 UTC, lohausr commented on doc/source/concept.rst
> +    :alt: The figure shows the bell-shaped ortholog KS distribution obtained for palm and rice approximated to a vertical line passing through the estimated mode (1.53 KS). A thin colored rectangular
Why is this legend in ``alt``?

2021-03-15 15:24 UTC, lohausr commented on doc/source/concept.rst
> +    :alt: In this figure the mixed plot shows the rate-adjusted ortholog KS distribution for oil palm and rice as a vertical line superimposed to the paralog KS distribution of oil palm. The vertical
Why is this legend in alt?

2021-03-15 15:24 UTC, lohausr commented on doc/source/concept.rst
> +    The ortholog *K*:sub:`S` estimate (red vertical line) has been shifted towards left after rate-adjustment, as highlighted by the red arrows starting from the original position and pointing at the
Why two separate and different legends? Combine.

2021-03-15 15:24 UTC, lohausr commented on doc/source/concept.rst
> +The ortholog *K*:sub:`S` estimate of palm-rice is then adjusted by rescaling it as twice the branch contribution of palm (*K*:sub:`S` --> 0.365 + 0.365 = 0.73). The position of the divergence line re
We could add that this likely matches the proposed monocot tau event.

2021-03-20 14:49 UTC, Cecilia-Sensalari commented
- Reorganized output files/folders list
- Described ks.tsv file format
- Described ELMM and LMM TSV file format

2021-03-23 22:13 UTC, lohausr requested changes
A few more edits and comments.

2021-03-23 22:13 UTC, lohausr commented on doc/source/input_output.rst
> +    * Databases storing the ortholog *K*:sub:`S` lists (``ks_list_database_path.txt``) and the estimated divergence time *K*:sub:`S` estimate (``peak_database_path.txt``) of the ortholog *K*:sub:`S`
```suggestion
    * ``ortholog_peak_db.tsv`` is a tabular data file storing the *K*:sub:`S` mode estimate from the ortholog *K*:sub:`S` distribution of species pairs. The name and location can be customised in the *ksrates* configuration file.
    * ``ortholog_ks_list_db.tsv`` is a tabular data file storing the ortholog *K*:sub:`S` value lists of species pairs.  The name and location can be customised in the *ksrates* configuration file.
```

2021-03-23 22:13 UTC, lohausr commented on doc/source/input_output.rst
> +    * List of commands to launch the ortholog *wgd* runs in the manual pipeline (``wgd_runs_species.txt``). Note that this file is not generated if launching the Nextflow pipeline.
```suggestion
    * ``wgd_runs_species.txt`` contains a list of *ksrates* commands to launch the *wgd* paralog and ortholog analysis when using the manual pipeline (see :ref:`run-example-case-as-a-manual-pipeline`). Note that this file is not generated if using the *ksrates* Nextflow pipeline.
```

2021-03-23 22:13 UTC, lohausr commented on doc/source/input_output.rst
> +    * The ``work`` directory is automatically generated by Nextflow to handle process organization and communication between processes (for more details see Nextflow documentation, e.g. the Get start
```suggestion
    * ``work``: when using the *ksrates* Nextflow pipeline this directory is automatically generated by Nextflow to handle process organization and communication between processes (for more details, see the Nextflow documentation, e.g. `here <https://www.nextflow.io/docs/latest/getstarted.html#your-first-script>`__).
```

2021-03-24 16:59 UTC, Cecilia-Sensalari commented
- Tables updated with isopub.txt check and cross symbols
- Removed distribution_peak_estimate parameter from expert config files
- Applied suggestions in review
- Added preprint citation in "How to cite us" page

2021-03-25 07:32 UTC, lohausr requested changes
A few more small changes.

2021-03-25 07:32 UTC, lohausr commented on doc/source/citation_acknowledgement.rst
> +Sensalari C., Lohaus R. and Maere S. 2021. *ksrates: positioning whole-genome duplications relative to speciation events using rate-adjusted mixed paralog–ortholog KS distributions*. bioRxiv doi: htt
```suggestion
Sensalari C., Maere S. and Lohaus R. (2021) *ksrates*: positioning whole-genome duplications relative to speciation events using rate-adjusted mixed paralog--ortholog  *K*:sub:`S` distributions. *bioRxiv* 2021.02.28.433234 `doi: https://doi.org/10.1101/2021.02.28.433234 <https://doi.org/10.1101/2021.02.28.433234>`__ 
```

2021-03-25 07:32 UTC, lohausr commented on doc/source/citation_acknowledgement.rst
> +Preprint deposited in bioRxiv:
```suggestion
If you publish results generated using *ksrates*, please cite:
```

2021-03-25 07:32 UTC, lohausr commented on doc/source/configuration.rst
> -* **distribution_peak_estimate**: the statistical method used to obtain a single ortholog *K*:sub:`S` estimate for the divergence time of a species pair from its ortholog distribution or to obtain a
Is this already consistently removed everywhere? Also in the code? Might be a bit early, it's also still in the preprint.

2021-03-25 09:29 UTC, merged